version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-225-162-157.compute-1.amazonaws.com
            port: '5432'
            database: d5ipjqlogvfo3a
            ssl: true
            user: uuacmchekaepsv
            password: e6c1c99bb033fe9e385747b76ecb63f31750469b5f5c0bd0afc66660b01e09dc
            migrations: true