version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-35-153-12-59.compute-1.amazonaws.com
            port: '5432'
            database: dfootgjm23g6fb
            ssl: true
            user: dfmjemlvfhqswa
            password: 682bb20c0993673d09cdd83d0efdee5df3aedbe8281fc431bd30918df16363f4
            migrations: true