version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-236-215-156.compute-1.amazonaws.com
            port: '5432'
            database: d2n4blbn4n90va
            ssl: true
            user: jgwuutjdxcpsmd
            password: babbc9dea6ea45e6f71b329c9f06f0c9a0701ff0f161fe4837bffc39558c4c34
            migrations: true